# Generated by Django 5.2.4 on 2025-07-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(choices=[('Choutuppal', 'Choutuppal'), ('Yacharam', 'Yacharam'), ('Kothur', 'Kothur'), ('Other', 'Other')], max_length=20)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
